allowBuilds:
  core-js-pure: false
  dtrace-provider: false
  protobufjs: false
  re2: true

ignoredBuiltDependencies:
  - better-sqlite3
  - core-js-pure
  - protobufjs

onlyBuiltDependencies:
  - re2
